IF(WITH_ASAN)
  message(STATUS "[TRUSTDBLE] Enabling address sanitizer")
  set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}  -fsanitize=address -fno-omit-frame-pointer")
  set (CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fsanitize=address -fno-omit-frame-pointer")
ENDIF()